nodeLinker: node-modules
enableGlobalCache: true
enableTelemetry: false

# CI build settings
checksumBehavior: "update"
enableImmutableInstalls: false
nmMode: hardlinks-local

pnpEnableEsmLoader: false
pnpEnableInlining: false
pnpMode: loose

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0069
    level: discard
  - code: YN0086
    level: discard
  - code: YN0032
    level: discard
  - code: YN0061
    level: discard
  - code: YN0028
    level: discard

packageExtensions:
  "@sentry/opentelemetry@*":
    peerDependencies:
      "@opentelemetry/context-async-hooks": "*"
      "@opentelemetry/core": "*"
      "@opentelemetry/instrumentation": "*" 
      "@opentelemetry/sdk-trace-base": "*"
  "next-auth@*":
    peerDependencies:
      "next": "*"
      "react": "*"
  "@radix-ui/react-select@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "typescript-eslint@*":
    peerDependencies:
      "typescript": "*"
