export const env = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  EXTERNAL_LOGGING_URL: process.env.EXTERNAL_LOGGING_URL,
  EXTERNAL_LOGGING_API_KEY: process.env.EXTERNAL_LOGGING_API_KEY,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
};
