name: Sync Environment Variables

on:
  push:
    paths:
      - '.env.*'
  workflow_dispatch:

jobs:
  sync-env:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PA_TOKEN }}

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Configure GitHub CLI
        run: |
          echo "${{ secrets.GH_PA_TOKEN }}" | gh auth login --with-token

      - name: Sync Production Environment
        if: github.ref == 'refs/heads/main'
        run: |
          # Read .env.production and set as secrets
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            key=$(echo "$key" | tr -d ' ')
            value=$(echo "$value" | tr -d '"' | tr -d "'")
            echo "$value" | gh secret set "$key" --env production
          done < .env.production

      - name: Sync Preview Environment
        if: github.ref != 'refs/heads/main'
        run: |
          # Read .env.preview and set as secrets
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            key=$(echo "$key" | tr -d ' ')
            value=$(echo "$value" | tr -d '"' | tr -d "'")
            echo "$value" | gh secret set "$key" --env preview
          done < .env.preview

      - name: Sync Supabase Specific Secrets
        run: |
          # Set Supabase specific secrets
          echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | gh secret set SUPABASE_ACCESS_TOKEN
          echo "${{ secrets.SUPABASE_PROJECT_ID }}" | gh secret set SUPABASE_PROJECT_ID
          echo "${{ secrets.SUPABASE_URL }}" | gh secret set SUPABASE_URL
          echo "${{ secrets.SUPABASE_ANON_KEY }}" | gh secret set SUPABASE_ANON_KEY
          echo "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" | gh secret set SUPABASE_SERVICE_ROLE_KEY
          echo "${{ secrets.SUPABASE_JWT_SECRET }}" | gh secret set SUPABASE_JWT_SECRET
